apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: unqh2c6oh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unqh2c6oh-python 
  name: unqh2c6oh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: unqh2c6oh-python 
